describe('Formulário', () => {
  it('Preencher todos os dados do formulário e Enviar', () => {
    cy.viewport(1900, 1080)
    cy.visit('/automation-practice-form')
    cy.get('#firstName').type('João')
    cy.get('#lastName').type('Silva')
    cy.get('#userEmail').type('joao.silva@gmail.com')
    cy.get('label[for=gender-radio-1]').click()
    cy.get('#userNumber').type('83991001122')
    cy.get('#dateOfBirthInput').type('{selectall}25 Oct 1994{enter}')
    cy.get('#subjectsInput').type('Computer Science{enter}')
    cy.get('label[for=hobbies-checkbox-2]').click()
    cy.get('#uploadPicture').attachFile('r2d2.png')
    cy.get('#currentAddress').type('Rua dos Engenheiros, Número 42')
    cy.get('#state').click()
    cy.get('#react-select-3-input').type('NCR{enter}')
    cy.get('#city').click()
    cy.get('#react-select-4-input').type('Noida{enter}')
    cy.get('#submit').click()
  })
})